language: ruby
rvm:
- 2.4.2
before_script:
- bundle install
script:
- bundle exec rspec
notifications:
  slack:
    secure: GLfnfzNovJSFetYJV29QuFeRcSzFeUlRDsyxo8v2ql72LOs3XNu4jus+1pjZKBQp2xgsdV16i5Xw9bL4Jtqwiq1uTs3HYA/OUPhSyo+UhVHrbPEyVo9Wr9gYUfXo008KqaqPOPIAmamJ/iGYwJkF8uh4HLvvNFhco4NOUN1iqHYN+TiQ58secprLyFRsoofohzEBc+pO9R7SrY6ZSvNZYQG/kg2ASAPKuikT/+IoxxBbCAzo5mCJfrl2T4fk7Tvz8fcpa3z2XH/80pA8TMMUJMM54OKELqWgDLHG/vY05oniFYklrnNfkAmnQ7Z2IRboAEoHskoa3Z2XbOQB2IYqxIrClog4zMp4U2FfS9rLAD0/NHDyNNSLy8+X8FwxURqDm+cvQO5EevZlI5L0Kw68KX3CWnFGFYdfblHByD2x5a/WnyVuZ5qBt6KfHN/NT+9yrBN5mv3zW5s2CSoPqq1bbvsKEyqoq+ddCcnoWoDPiR22wdRLvO6NWSD+NFiQ4z6NMCYyDAbbXudJdWPO+l86DagRhV9Irk+L0HnX+Jf9Z8vKwCZ6QbG+dqvoMFutuyIWt2cHn469ZWoS3rtyF/jM5u4IjC6IMINXiyuxlFHJdacvmt+R6/TjXTw2ExSSFW+cAZLPfTR/VrlIY4bWOoIrWm6oa4xvOzKM4UOQz6/Sn3c=
